package check

import (
	"github.com/desilang/desi/compiler/internal/ast"
	"github.com/desilang/desi/compiler/internal/diag"
)

// usageTracker collects binding locations for import/from-item names and
// computes usage counts using both the checker's resolved Idents map and
// the set of typed expressions (so call-site and qualifier uses are seen).
type usageTracker struct {
	importLoc  map[string]diag.Span // local name -> span (for "import …")
	fromLoc    map[string]diag.Span // local name -> span (for "from … import …")
	usedImport map[string]int
	usedFrom   map[string]int
}

// newUsageTracker scans the module's __top__ for import/from statements and records
// binding locations (preferring alias spans when present).
func newUsageTracker(mod *ast.Module) *usageTracker {
	u := &usageTracker{
		importLoc:  map[string]diag.Span{},
		fromLoc:    map[string]diag.Span{},
		usedImport: map[string]int{},
		usedFrom:   map[string]int{},
	}
	if mod == nil {
		return u
	}
	// Find the synthetic __top__ function generated by the parser.
	var top *ast.FuncDecl
	for _, d := range mod.Decls {
		if fn, ok := d.(*ast.FuncDecl); ok && fn.Name.Name == "__top__" {
			top = fn
			break
		}
	}
	if top == nil || top.Body == nil {
		return u
	}

	for _, st := range top.Body.Stmts {
		switch s := st.(type) {
		case *ast.ImportStmt:
			local := ""
			if s.Alias != nil {
				local = s.Alias.Name
			} else if n := len(s.Path); n > 0 {
				local = s.Path[n-1]
			}
			if local != "" {
				sp := s.Span
				if s.Alias != nil {
					sp = s.Alias.Span
				}
				u.importLoc[local] = sp
			}

		case *ast.FromImportStmt:
			for _, it := range s.Items {
				local := it.Name.Name
				sp := it.Span
				if it.Alias != nil {
					local = it.Alias.Name
					sp = it.Alias.Span
				}
				if local != "" {
					u.fromLoc[local] = sp
				}
			}
		}
	}
	return u
}

// countUsesFromIdents increments usage counters based on resolved identifiers.
// We intentionally match by identifier NAME against the recorded binding tables.
// (Some call paths don't store the callee ident in Info.Idents.)
func (u *usageTracker) countUsesFromIdents(idmap map[*ast.Ident]*Symbol) {
	for id := range idmap {
		if _, ok := u.importLoc[id.Name]; ok {
			u.usedImport[id.Name]++
		}
		if _, ok := u.fromLoc[id.Name]; ok {
			u.usedFrom[id.Name]++
		}
	}
}

// countUsesFromTypes scans typed expressions so we see:
//   - bare callee names:    sum(…)
//   - module qualifiers:    io.println(…)
func (u *usageTracker) countUsesFromTypes(info *Info) {
	for expr := range info.Types {
		// Calls: look at callee
		if call, ok := expr.(*ast.CallExpr); ok {
			switch cal := call.Callee.(type) {
			case *ast.Ident:
				if _, ok := u.fromLoc[cal.Name]; ok {
					u.usedFrom[cal.Name]++
				}
				if _, ok := u.importLoc[cal.Name]; ok {
					u.usedImport[cal.Name]++
				}
			case *ast.FieldExpr:
				// io.println(...) -> mark 'io' as used if it is an import
				if recv, ok := cal.X.(*ast.Ident); ok {
					if _, ok := u.importLoc[recv.Name]; ok {
						u.usedImport[recv.Name]++
					}
				}
			}
			continue
		}
		// Standalone selectors also count as using the qualifier.
		if sel, ok := expr.(*ast.FieldExpr); ok {
			if recv, ok := sel.X.(*ast.Ident); ok {
				if _, ok := u.importLoc[recv.Name]; ok {
					u.usedImport[recv.Name]++
				}
			}
		}
	}
}

// emitUnusedDiags returns DMW0004/DMW0005 diagnostics for bindings never used.
func (u *usageTracker) emitUnusedDiags() []diag.Diagnostic {
	var out []diag.Diagnostic
	for name, sp := range u.importLoc {
		if u.usedImport[name] == 0 {
			out = append(out, diag.Diagnostic{
				CodeID:  "DMW0004",
				Domain:  "module",
				Title:   "",
				Message: "unused import '" + name + "'",
				Primary: diag.Label{Span: sp, Primary: true},
			})
		}
	}
	for name, sp := range u.fromLoc {
		if u.usedFrom[name] == 0 {
			out = append(out, diag.Diagnostic{
				CodeID:  "DMW0005",
				Domain:  "module",
				Title:   "",
				Message: "unused imported name '" + name + "'",
				Primary: diag.Label{Span: sp, Primary: true},
			})
		}
	}
	return out
}
