package c

import (
	"bytes"

	"github.com/desilang/desi/compiler/internal/ast"
	"github.com/desilang/desi/compiler/internal/check"
	"github.com/desilang/desi/compiler/internal/term"
)

// EmitFile is the public entry point for C code emission.
func EmitFile(f *ast.File, info *check.Info) string {
	var b bytes.Buffer
	term.Wprintf(&b, "/* generated by desic (Stage-1) */\n")
	term.Wprintf(&b, "#include <stdint.h>\n")
	term.Wprintf(&b, "#include <stdio.h>\n")
	term.Wprintf(&b, "#include <string.h>\n") // strcmp
	term.Wprintf(&b, "#include \"desi_std.h\"\n\n")

	// Emit typedefs for all struct declarations directly from the AST.
	for _, d := range f.Decls {
		if sd, ok := d.(*ast.StructDecl); ok {
			emitStructTypedef(&b, sd, info)
			term.Wprintf(&b, "\n\n")
		}
	}

	sigs := collectFuncSigs(f)

	// Prototypes for non-main
	for _, d := range f.Decls {
		if fn, ok := d.(*ast.FuncDecl); ok && fn.Name != "main" {
			term.Wprintf(&b, "static %s %s(%s);\n",
				cType(typeToKind(fn.Ret)), fn.Name, cParamList(fn, info))
		}
	}
	if len(sigs) > 0 {
		term.Wprintf(&b, "\n")
	}

	// Definitions (non-main first)
	for _, d := range f.Decls {
		if fn, ok := d.(*ast.FuncDecl); ok && fn.Name != "main" {
			emitFunc(&b, fn, sigs, info, false)
			term.Wprintf(&b, "\n")
		}
	}
	// Main last
	if m := findMain(f); m != nil {
		emitFunc(&b, m, sigs, info, true)
	}
	return b.String()
}
