package c

import (
	"bytes"
	"strconv"

	"github.com/desilang/desi/compiler/internal/ast"
	"github.com/desilang/desi/compiler/internal/check"
	"github.com/desilang/desi/compiler/internal/term"
)

// EmitFile is the public entry point for C code emission.
func EmitFile(f *ast.File, info *check.Info) string {
	var b bytes.Buffer
	term.Wprintf(&b, "/* generated by desic (Stage-1) */\n")
	term.Wprintf(&b, "#include <stdint.h>\n")
	term.Wprintf(&b, "#include <stdio.h>\n")
	term.Wprintf(&b, "#include <string.h>\n") // strcmp
	term.Wprintf(&b, "#include <stdlib.h>\n") // malloc/free for async futures
	term.Wprintf(&b, "#include \"desi_std.h\"\n\n")

	// NEW: validate the file for C-backend constraints and emit #error lines if any.
	if errs := validateForCBackend(f, info); len(errs) > 0 {
		for _, m := range errs {
			term.Wprintf(&b, "#error %s\n", m)
		}
		term.Wprintf(&b, "\n")
	}

	// Emit typedefs for all struct declarations directly from the AST.
	for _, d := range f.Decls {
		if sd, ok := d.(*ast.StructDecl); ok {
			emitStructTypedef(&b, sd, info)
			term.Wprintf(&b, "\n\n")
		}
	}

	// Emit typedefs for all enum declarations.
	for _, d := range f.Decls {
		if ed, ok := d.(*ast.EnumDecl); ok {
			emitEnumTypedef(&b, ed, info)
			term.Wprintf(&b, "\n")
		}
	}

	// ---- NEW: #define macros for top-level constants in this file ----
	for _, d := range f.Decls {
		cd, ok := d.(*ast.ConstDecl)
		if !ok {
			continue
		}
		name := cd.Name
		switch v := cd.Value.(type) {
		case *ast.IntLit:
			if hasPrefixAny(v.Value, "0b", "0B") {
				if n, err := strconv.ParseInt(v.Value[2:], 2, 64); err == nil {
					term.Wprintf(&b, "#define %s %d\n", name, n)
				} else {
					term.Wprintf(&b, "#define %s 0\n", name)
				}
			} else {
				term.Wprintf(&b, "#define %s %s\n", name, v.Value)
			}
		case *ast.BoolLit:
			if v.Value {
				term.Wprintf(&b, "#define %s 1\n", name)
			} else {
				term.Wprintf(&b, "#define %s 0\n", name)
			}
		case *ast.StrLit:
			term.Wprintf(&b, "#define %s %s\n", name, ensureCStringLiteral(v.Value))
		default:
			term.Wprintf(&b, "#define %s 0\n", name)
		}
	}
	if hasAnyConst(f) {
		term.Wprintf(&b, "\n")
	}

	// NOTE: struct-aware signatures (params + returns)
	sigs := collectFuncSigs(f, info)

	// Prototypes for non-main
	for _, d := range f.Decls {
		if fn, ok := d.(*ast.FuncDecl); ok && fn.Name != "main" {
			if fn.Async {
				term.Wprintf(&b, "static struct desi_future %s(%s);\n", fn.Name, cParamList(fn, info))
			} else {
				term.Wprintf(&b, "static %s %s(%s);\n",
					cType(typeToKindOrStruct(fn.Ret, info)), fn.Name, cParamList(fn, info))
			}
		}
	}
	if len(sigs) > 0 {
		term.Wprintf(&b, "\n")
	}

	// Definitions (non-main first)
	for _, d := range f.Decls {
		if fn, ok := d.(*ast.FuncDecl); ok && fn.Name != "main" {
			emitFunc(&b, fn, sigs, info, false)
			term.Wprintf(&b, "\n")
		}
	}
	// Main last
	if m := findMain(f); m != nil {
		emitFunc(&b, m, sigs, info, true)
	}
	return b.String()
}

func hasAnyConst(f *ast.File) bool {
	for _, d := range f.Decls {
		if _, ok := d.(*ast.ConstDecl); ok {
			return true
		}
	}
	return false
}
